In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('/content/drive/MyDrive/Projects/Medicine_recommender/Training.csv')

In [5]:
df.head(5)

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [6]:
df.shape

(4920, 133)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB

In [8]:
df.duplicated().sum()

np.int64(4616)

In [9]:
df.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [10]:
len(df['prognosis'].unique())

41

In [11]:
x=df.drop('prognosis',axis=1)
y=df['prognosis']

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [13]:
le.classes_

array(['(vertigo) Paroymsal  Positional Vertigo', 'AIDS', 'Acne',
       'Alcoholic hepatitis', 'Allergy', 'Arthritis', 'Bronchial Asthma',
       'Cervical spondylosis', 'Chicken pox', 'Chronic cholestasis',
       'Common Cold', 'Dengue', 'Diabetes ',
       'Dimorphic hemmorhoids(piles)', 'Drug Reaction',
       'Fungal infection', 'GERD', 'Gastroenteritis', 'Heart attack',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Hypertension ', 'Hyperthyroidism', 'Hypoglycemia',
       'Hypothyroidism', 'Impetigo', 'Jaundice', 'Malaria', 'Migraine',
       'Osteoarthristis', 'Paralysis (brain hemorrhage)',
       'Peptic ulcer diseae', 'Pneumonia', 'Psoriasis', 'Tuberculosis',
       'Typhoid', 'Urinary tract infection', 'Varicose veins',
       'hepatitis A'], dtype=object)

In [14]:
le.transform(le.classes_)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40])

In [15]:
map=dict(zip(le.classes_,le.transform(le.classes_)))

In [16]:
map

{'(vertigo) Paroymsal  Positional Vertigo': np.int64(0),
 'AIDS': np.int64(1),
 'Acne': np.int64(2),
 'Alcoholic hepatitis': np.int64(3),
 'Allergy': np.int64(4),
 'Arthritis': np.int64(5),
 'Bronchial Asthma': np.int64(6),
 'Cervical spondylosis': np.int64(7),
 'Chicken pox': np.int64(8),
 'Chronic cholestasis': np.int64(9),
 'Common Cold': np.int64(10),
 'Dengue': np.int64(11),
 'Diabetes ': np.int64(12),
 'Dimorphic hemmorhoids(piles)': np.int64(13),
 'Drug Reaction': np.int64(14),
 'Fungal infection': np.int64(15),
 'GERD': np.int64(16),
 'Gastroenteritis': np.int64(17),
 'Heart attack': np.int64(18),
 'Hepatitis B': np.int64(19),
 'Hepatitis C': np.int64(20),
 'Hepatitis D': np.int64(21),
 'Hepatitis E': np.int64(22),
 'Hypertension ': np.int64(23),
 'Hyperthyroidism': np.int64(24),
 'Hypoglycemia': np.int64(25),
 'Hypothyroidism': np.int64(26),
 'Impetigo': np.int64(27),
 'Jaundice': np.int64(28),
 'Malaria': np.int64(29),
 'Migraine': np.int64(30),
 'Osteoarthristis': np.int64(31),
 'Paralysis (brain hemorrhage)': np.int64(32),
 'Peptic ulcer diseae': np.int64(33),
 'Pneumonia': np.int64(34),
 'Psoriasis': np.int64(35),
 'Tuberculosis': np.int64(36),
 'Typhoid': np.int64(37),
 'Urinary tract infection': np.int64(38),
 'Varicose veins': np.int64(39),
 'hepatitis A': np.int64(40)}

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [18]:
x_train.shape

(3936, 132)

In [19]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [20]:
models={
    'SVC':SVC(),
    'RandomForestClassifier':RandomForestClassifier(),
    'DecisionTreeClassifier':DecisionTreeClassifier(),
    'LogisticRegression':LogisticRegression(),
    'KNeighborsClassifier':KNeighborsClassifier()
}

In [21]:
#Iterating and fitting the models one by one
for name,model in models.items():
  model.fit(x_train,y_train)
  y_pred=model.predict(x_test) #predicting using each model
  print(f"Accuracy score of {name} is {accuracy_score(y_test,y_pred)}")
  print(confusion_matrix(y_test,y_pred))
  print()

Accuracy score of SVC is 1.0
[[22  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 30 ...  0  0  0]
 ...
 [ 0  0  0 ... 18  0  0]
 [ 0  0  0 ...  0 19  0]
 [ 0  0  0 ...  0  0 24]]

Accuracy score of RandomForestClassifier is 1.0
[[22  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 30 ...  0  0  0]
 ...
 [ 0  0  0 ... 18  0  0]
 [ 0  0  0 ...  0 19  0]
 [ 0  0  0 ...  0  0 24]]

Accuracy score of DecisionTreeClassifier is 1.0
[[22  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 30 ...  0  0  0]
 ...
 [ 0  0  0 ... 18  0  0]
 [ 0  0  0 ...  0 19  0]
 [ 0  0  0 ...  0  0 24]]

Accuracy score of LogisticRegression is 1.0
[[22  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 30 ...  0  0  0]
 ...
 [ 0  0  0 ... 18  0  0]
 [ 0  0  0 ...  0 19  0]
 [ 0  0  0 ...  0  0 24]]

Accuracy score of KNeighborsClassifier is 1.0
[[22  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 30 ...  0  0  0]
 ...
 [ 0  0  0 ... 18  0  0]
 [ 0  0  0 ...  0 19  0]
 [ 0  0  0 ...  0  0 24]]

# Building Recommendation System

In [22]:
symptoms=pd.read_csv('/content/drive/MyDrive/Projects/Medicine_recommender/symtoms_df.csv')

In [23]:
precautions=pd.read_csv('/content/drive/MyDrive/Projects/Medicine_recommender/precautions_df.csv')

In [24]:
workouts=pd.read_csv('/content/drive/MyDrive/Projects/Medicine_recommender/workout_df.csv')
medications=pd.read_csv('/content/drive/MyDrive/Projects/Medicine_recommender/medications.csv')
description=pd.read_csv('/content/drive/MyDrive/Projects/Medicine_recommender/description.csv')
diets=pd.read_csv('/content/drive/MyDrive/Projects/Medicine_recommender/diets.csv')

In [25]:
symp_dict=dict(zip(le.classes_,le.transform(le.classes_)))

In [26]:
svc = SVC()
svc.fit(x_train, y_train)

def predict(symptoms_seen):
    input_vector = np.zeros(len(x.columns))

    for symptom in symptoms_seen:
        if symptom in x.columns:
            input_vector[x.columns.get_loc(symptom)] = 1

    prediction = svc.predict([input_vector])[0]

    return le.inverse_transform([prediction])[0]

In [27]:
symptoms_input=input("provide the symptoms seperated by comma:")
user_symptoms=[]
for symptom in symptoms_input.split(','):
  user_symptoms.append(symptom.strip())

predicted_disease=predict(user_symptoms)
print(predicted_disease)

provide the symptoms seperated by comma:itching, skin_rash, nodal_skin_eruptions
Fungal infection

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [28]:
print(description.head())
print()
print(precautions.head())
print()
print(workouts.head())
print()
print(medications.head())
print()
print(diets.head())

               Disease                                        Description
0     Fungal infection  Fungal infection is a common skin condition ca...
1              Allergy  Allergy is an immune system reaction to a subs...
2                 GERD  GERD (Gastroesophageal Reflux Disease) is a di...
3  Chronic cholestasis  Chronic cholestasis is a condition where bile ...
4        Drug Reaction  Drug Reaction occurs when the body reacts adve...

   Unnamed: 0         Disease                      Precaution_1  \
0           0   Drug Reaction                   stop irritation
1           1         Malaria          Consult nearest hospital
2           2         Allergy                    apply calamine
3           3  Hypothyroidism                     reduce stress
4           4       Psoriasis  wash hands with warm soapy water

                   Precaution_2        Precaution_3  \
0      consult nearest hospital    stop taking drug
1               avoid oily food  avoid non veg food
2       cover area with bandage                 NaN
3                      exercise         eat healthy
4  stop bleeding using pressure      consult doctor

                  Precaution_4
0                    follow up
1           keep mosquitos out
2  use ice to compress itching
3             get proper sleep
4                   salt baths

   Unnamed: 0.1  Unnamed: 0           disease                    workout
0             0           0  Fungal infection         Avoid sugary foods
1             1           1  Fungal infection         Consume probiotics
2             2           2  Fungal infection  Increase intake of garlic
3             3           3  Fungal infection     Include yogurt in diet
4             4           4  Fungal infection      Limit processed foods

               Disease                                         Medication
0     Fungal infection  ['Antifungal Cream', 'Fluconazole', 'Terbinafi...
1              Allergy  ['Antihistamines', 'Decongestants', 'Epinephri...
2                 GERD  ['Proton Pump Inhibitors (PPIs)', 'H2 Blockers...
3  Chronic cholestasis  ['Ursodeoxycholic acid', 'Cholestyramine', 'Me...
4        Drug Reaction  ['Antihistamines', 'Epinephrine', 'Corticoster...

               Disease                                               Diet
0     Fungal infection  ['Antifungal Diet', 'Probiotics', 'Garlic', 'C...
1              Allergy  ['Elimination Diet', 'Omega-3-rich foods', 'Vi...
2                 GERD  ['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'...
3  Chronic cholestasis  ['Low-Fat Diet', 'High-Fiber Diet', 'Lean prot...
4        Drug Reaction  ['Antihistamine Diet', 'Omega-3-rich foods', '...

In [29]:
#Function for all recommendations
def get_recommendations(disease):

    result = {}

    # Description
    result["description"] = description[
        description["Disease"] == disease
    ]["Description"].values

    # Precautions
    result["precautions"] = precautions[
        precautions["Disease"] == disease
    ].values

    # Workout
    result["workout"] = workouts[
        workouts["disease"] == disease
    ]["workout"].values

    # Medication
    result["medications"] = medications[
        medications["Disease"] == disease
    ]["Medication"].values

    # Diet
    result["diet"] = diets[
        diets["Disease"] == disease
    ]["Diet"].values

    return result

In [30]:
recommendations = get_recommendations(predicted_disease)

print("Disease:", predicted_disease)
print("\nDescription:", recommendations["description"])
print("\nPrecautions:", recommendations["precautions"])
print("\nWorkout:", recommendations["workout"])
print("\nMedications:", recommendations["medications"])
print("\nDiet:", recommendations["diet"])

Disease: Fungal infection

Description: ['Fungal infection is a common skin condition caused by fungi.']

Precautions: [[27 'Fungal infection' 'bath twice' 'use detol or neem in bathing water'
  'keep infected area dry' 'use clean cloths']]

Workout: ['Avoid sugary foods' 'Consume probiotics' 'Increase intake of garlic'
 'Include yogurt in diet' 'Limit processed foods' 'Stay hydrated'
 'Consume green tea' 'Eat foods rich in zinc' 'Include turmeric in diet'
 'Eat fruits and vegetables']

Medications: ["['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']"]

Diet: ["['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']"]

# Combining both Function

In [34]:
def Health_Recommendation():
  Symptoms_Seen=input("provide the symptoms seperated by comma:")

  #convert input to list
  user_symptoms=[]
  for symptoms in Symptoms_Seen.split(','):
    user_symptoms.append(symptoms.strip().lower())

  #creating input vector for the model
  input_vector=np.zeros(len(x.columns))
  valid_symptoms=[]

  for symptoms in user_symptoms:
    input_vector[x.columns.get_loc(symptoms)]=1
    valid_symptoms.append(symptoms)

  #checking whether symptoms are valid
  if len(valid_symptoms)==0:
    print('symptoms entered are invalid')
    return

  #Predicting disease
  prediction=svc.predict([input_vector])[0]
  predicted_disease=le.inverse_transform([prediction])[0]

  #Description
  disease_description=description[description['Disease']==predicted_disease]['Description'].iloc[0]

  #Precautions
  precautions_row=precautions[precautions['Disease']==predicted_disease]
  disease_precautions=precautions_row[
      ["Precaution_1", "Precaution_2",
         "Precaution_3", "Precaution_4"]
  ].iloc[0].tolist()

  #Workouts
  workout_list=workouts[workouts["disease"] == predicted_disease]["workout"].tolist()

  #Medication
  medication = medications[medications["Disease"] == predicted_disease]["Medication"].iloc[0]

  #Diets
  diet = diets[diets["Disease"] == predicted_disease]["Diet"].iloc[0]

  #Displaying everything

  print("\n" + "*"*50)
  print("             HEALTH RECOMMENDATION")
  print("*"*50)

  print("\nSymptoms entered:")
  print(", ".join(valid_symptoms))

  print("\nPredicted Disease:")
  print(predicted_disease)

  print("\nDescription:")
  print(disease_description)

  print("\nPrecautions:")
  for p in disease_precautions:
     print("-", p)

  print("\nWorkout:")
  for w in workout_list:
    print("-", w)

  import ast
  medication_list=ast.literal_eval(medication)
  diet_list=ast.literal_eval(diet)

  print("\nDiet:")
  for d in diet_list:
    print('-',d)

  print("\nMedication Information:")
  for m in medication_list:
    print('-',m)

  print("\n" + "*"*50)

In [35]:
Health_Recommendation()

provide the symptoms seperated by comma:itching, skin_rash, nodal_skin_eruptions

**************************************************
             HEALTH RECOMMENDATION
**************************************************

Symptoms entered:
itching, skin_rash, nodal_skin_eruptions

Predicted Disease:
Fungal infection

Description:
Fungal infection is a common skin condition caused by fungi.

Precautions:
- bath twice
- use detol or neem in bathing water
- keep infected area dry
- use clean cloths

Workout:
- Avoid sugary foods
- Consume probiotics
- Increase intake of garlic
- Include yogurt in diet
- Limit processed foods
- Stay hydrated
- Consume green tea
- Eat foods rich in zinc
- Include turmeric in diet
- Eat fruits and vegetables

Diet:
- Antifungal Diet
- Probiotics
- Garlic
- Coconut oil
- Turmeric

Medication Information:
- Antifungal Cream
- Fluconazole
- Terbinafine
- Clotrimazole
- Ketoconazole

**************************************************

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(